alphagov/manuals-frontend

- app/assets/javascripts/collapsible_collection.js
- app/assets/stylesheets/_manuals-print.scss
- app/assets/stylesheets/application.scss
- app/views/manuals/show.html.erb
- app/views/manuals/updates.html.erb
- spec/javascripts/collapsible_collection_spec.js
The `<div class="title-controls-wrap">` us only used if the JavaScript has loaded -its part of the controls used for the collapsible sections.
This PR removes this HTML from the templates and adds the JavaScript to build it after document.ready. This means if the JS hasn't loaded for whatever we don't have bits of HTML floating around that aren't used.
> Remove HTML only used by the JavaScript

- app/presenters/manual_presenter.rb
- app/views/manuals/_header.html.erb
- spec/features/viewing_a_manual_spec.rb
- spec/features/viewing_manual_updates_spec.rb
Using the singular fits the pattern of lots of other things, particularly in
Whitehall. This change was prompted by HMRC.
> "HMRC internal manuals" => "HMRC internal manual"

- app/controllers/manuals_controller.rb
Refactor the way manuals and documents are loaded and checked by the manuals controller. Push everything towards smaller methods with a single purpose. I believe these changes make it easier to see how the controller works, and will make it more straightforward to change the way manuals and documents are loaded in the future (eg as part of #132)
> Refactor manuals controller

- app/assets/stylesheets/_manuals-print.scss
Improvements made are to improve design and layout of the printed page
and to improve readability.
See screenshots attached for side by side comparisons.
(left image is after, right image is before)
Changes made -
• Hide 'open all' and 'close all' links
• Hide 'Give feedback about this page' link
• clear main content from floating up next to the header metadata
• Remove URLs displaying after header metadata links
• display dt's and dl's inline to match metadata format seen on other
publication formats
• update spacing for h1 in HMRC header to match on screen look closer
• bold h1 for clarity
• bold sub headings for clarity and better scanning
https://www.pivotaltracker.com/story/show/90180042
> Improvements to print stylesheets for manuals

- app/assets/stylesheets/_manuals-print.scss
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/manuals/_header.html.erb
Add print this page link to manuals to print full page even folded
sections on subsection pages.
To make printing easier/more obvious to users who want to print
manuals we've added a "Print this page" to all pages on manuals.
This works for HMRC manuals too.
• added the link to application.html.erb so that it appears on
all pages
• updated styles with input from Rebecca Cottrell on layout/spacing
• added default styles hide element, but included styles to show
element when javascript is enabled
• tested on mobile and IE6, 7, 8 and 9 and works as expected
https://www.pivotaltracker.com/story/show/88435406
manual before -
manual after -
HMRC before -
HMRC after -
> Add print this page link to manuals to print full page

- app/controllers/manuals_controller.rb
- app/helpers/application_helper.rb
- app/presenters/document_presenter.rb
- app/presenters/sibling_decorator.rb
- app/repositories/document_repository.rb
- app/views/manuals/show.html.erb
- spec/features/viewing_a_manual_spec.rb
- spec/support/app_helpers.rb
- spec/support/manual_helpers.rb
- spec/unit/sibling_decorator_spec.rb
This PR will allow users to navigate through sections within the HMRC manual.
ticket: https://www.pivotaltracker.com/story/show/88435524
all done with the help of the splendid @fatbusinessman, @alicebartlett and @evilstreak
> Add previous and next links to HMRC manual

- config/environments/production.rb
- config/environments/test.rb
Rails 4.2 deprecates `serve_static_assets` in favour of `serve_static_files`, producing the following warning during deploys:
> DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly.
> Update serve_static_assets config for Rails 4.2

- app/controllers/application_controller.rb
- app/controllers/manuals_controller.rb
- spec/features/viewing_a_manual_spec.rb
HMRC manuals on GOV.UK are not yet the canonical source. However all other manuals are, and those should be indexed by search engines so users can find them.
* Only exclude HMRC manuals from robots
cc @evilstreak @jamiecobbett @rooreynolds
Earlier attempt: https://github.com/alphagov/manuals-frontend/pull/138
> Prevent only HMRC manuals from being crawled

- app/helpers/application_helper.rb
**This shouldn't be merged until https://github.com/alphagov/static/pull/601 is merged and deployed**
**Note:** ~~I couldn't find any real manuals content with pagination to test against, so this is based on the test suite only :(~~ Tested it locally against `hmrc-internal-manuals/vat-government-and-public-bodies` and it looks OK.
We should only use one style of keys for objects used in components,
to avoid reduce confusion when using components. Consistency is good.
After discussion with @edds we agreed to use symbols as this makes
more sense in a ruby/rails environment.
The first step was to support both, as clients of those components
will still be sending string key'd objects and can't be updated
at the time as this app, so we have to;
1. [Update static components to support either …
> Use symbols, not strings, for component object keys

- app/assets/stylesheets/application.scss
The blue header block had a too-large negative margin which made it bigger than its container on smaller devices, creating a horizontal scroll.
Before:
After:
> Fix header margin on small screens.

- app/views/layouts/application.html.erb
- app/views/manuals/index.html.erb
- spec/features/viewing_a_manual_spec.rb
Part of improving search result snipperts shown on external search
engines. The lack of a meta-description tag makes some search result
snippets unhelpful, confusing, or misleading. Ticket:
https://trello.com/c/S6VUwRWQ/273-follow-up-add-meta-description-tag-to-custom-content-types
> Add meta description tag to manuals

- lib/tasks/publishing_api.rake
Now that a gone route for the Employment Income Manual is live, we can
remove the code which publishes this route from Manuals Frontend.
> Remove EIM route publishing

- app/presenters/manual_presenter.rb
- app/views/manuals/_header.html.erb
- This was used when searching within a manual as we stripped leading
slashes on all other occurrences of the manual slug. We shouldn't do
this anymore, because it breaks search within a manual in another way
(which required a temporary fix in frontend).
- Trello:
https://trello.com/c/KAR7YtA7/119-searching-within-a-manual-uses-the-wrong-layout.
> Don't strip leading slashes from the manual URL anymore

- app/views/manuals/show.html.erb
With the associated change in the Govspeak component, this commit
updates the call to it to set `rich_govspeak` to be `true`. This then
allows Manuals to have bold text within the body. This is required for
the Highway Code.
See https://github.com/alphagov/static/pull/657 for more information.
[Ticket](https://trello.com/c/eYyOkNRR/131-highway-code-manual-has-styled-strong-tags).
> Enable rich govspeak

- app/controllers/manuals_controller.rb
- spec/features/viewing_a_manual_spec.rb
- spec/support/manual_helpers.rb
`/updates` does not have its own content item, so when withdrawing a Manual a `gone` content item is published for the Manual and each of its sections but not `#{manual_slug}/updates`. When a User views `/updates` on a withdrawn Manual, Manuals Frontend will try to render the page with the `gone` content item that it has for the withdrawn Manual.
When that happens, the App will 500 and this will fall over to the cache, which has the `/updates` page cached and displays it.
Don't return a `content_item` for the Manual if it has a format of `gone`, allowing the App to 410 as would be expected.
This PR does just that and adds a failing test for this edgecase.
> 410 on updates with withdrawn manual

- app/assets/javascripts/application.js
- app/assets/javascripts/collapsible_collection.js
- spec/javascripts/collapsible_collection_spec.js
For https://trello.com/c/E6u89QxG/132-fix-manuals-linking-issue
Fixes the issue of clicking on a link (that links to another section within the same manual) not opening the appropriate section. The fix itself is just changing one line, but in order to write test for it, the code was refactored.
> Fix internal anchor links

- app/assets/javascripts/application.js
- app/assets/javascripts/collapsible.js
- app/assets/javascripts/collapsible_collection.js
- spec/javascripts/collapsible_collection_spec.js
- spec/javascripts/collapsible_spec.js
This fixes an issue for when a Collapsible would be opened by clicking on a link to it, a new Collapsible was created for it. In practice this meant that a collapsible could have an increasing number of clickable spans, which lead to unexpected such as a click not appearing to open a span (while actually the click was triggering the toggle open action twice, thereby opening and immediately closing the Collapsible). As part of the fix, some functionality was extracted to separate methods and respective Jasmine tests have been added.
> Fix multiple creation of close spans

- app/presenters/manual_presenter.rb
- app/views/manuals/_beta_label.html.erb
- app/views/manuals/_header.html.erb
We no longer want to provide a special message in the beta label for HMRC
content as the only manuals of theirs published here are not available in
their library.
For: https://trello.com/c/ZSSTBlqM/245-change-the-beta-label-on-hmrc-manuals
> Remove beta_message from ManualPresenter

- app/presenters/manual_presenter.rb
- spec/support/manual_helpers.rb
We're currently updating apps to support a new tagging architecture.
Part of this work includes changes to hmrc-manuals-api such that it sets
the organisation data in the links hash rather than the details hash.
This change to manuals-frontend ensures organisation data in the links
field of the manual payload is used in preference to data in details.
This will eventually be updated to drop usage of details altogether.
Trello: https://trello.com/c/6Owhx9Vn
> Update manual presenter to prefer links for organisation data

- README.md
The old URL has been removed. Use an alternative.
https://www.gov.uk/hmrc-internal-manuals/pensions-tax-manual
> Update HMRC manual URL in Readme

- app/controllers/manuals_controller.rb
- spec/features/viewing_a_manual_spec.rb
- spec/support/manual_helpers.rb
For https://trello.com/c/pl3zZeWr/257-add-caching-to-manuals-frontend
Manuals-frontend previously did not set any caching, so Rails by default prevents any caching (setting `Cache-Control: max-age=0, private, must-revalidate`).
This implementation is inspired by [`government-frontend`'s implementation of the `set_expiry` method](https://github.com/alphagov/government-frontend/commit/fe66f96c238be1c751c49f54871e2ffec93edcc6), setting cache headers based on the content items that are being presented.
> Add HTTP caching

- app/views/manuals/_header.html.erb
`role="breadcrumbs"` is not a thing.
https://www.w3.org/TR/wai-aria/roles#role_definitions
We previously removed from the component: https://github.com/alphagov/static/pull/737
Was added in: https://github.com/alphagov/manuals-frontend/pull/4
> Remove invalid breadcrumbs aria role

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/initializers/logstasher.rb
https://govuk.zendesk.com/agent/tickets/1414121
Manuals frontend is generating a lot of uninformative logging. As a first step to remedying this configure it to use logstasher and turn off application logs. I've based this on examples found in government-frontend, specialist-publisher-rebuild and publishing-api.
> Configure logstasher

- config/environments/production.rb
https://govuk.zendesk.com/agent/tickets/1414121
This config option switches off view logging which should reduce
the volume of useless log lines containing 'rendered foo/bar.erb...'
> Turn off view logging

- app/views/manuals/show.html.erb
- app/views/manuals/updates.html.erb
The meta description tag is used for the index page of a manual but none of the sub-pages. This commit adds meta description tags to all pages, the contents of which are set to the description associated with the manual. This adds descriptions to external search engine results when the pages are re-indexed.
Trello: https://trello.com/c/bbAwFAQ1/108-add-meta-descriptions-to-pages-missing-them
> Add meta descriptions

- app/presenters/manual_presenter.rb
- spec/features/viewing_a_manual_spec.rb
- spec/unit/manual_presenter_spec.rb
For: https://trello.com/c/J8ER0vhZ/64-remove-beta-label-from-manuals
The beta information is not in the content item so we just toggle on the HMRC-ness of the manual, which is enough for this story.
> Remove beta label from normal manuals, leave it for HMRC

- app/presenters/sibling_decorator.rb
- spec/unit/sibling_decorator_spec.rb
The content store contains some manuals child pages where the parent doesn't exist. This means that `parent` is nil so `parent.details` causes an error.
This change will allow the child page to render even when it doesn't have a parent.
> Wrap siblings method in guard conditional

- app/helpers/application_helper.rb
- app/presenters/manual_presenter.rb
- lib/tasks/publishing_api.rake
- spec/support/manual_helpers.rb
- spec/unit/application_helper_spec.rb
- spec/unit/manual_presenter_spec.rb
We've recently changed manuals-publisher so that it no longer sends dates
to the publishing-api when writing drafts or publishing.  This means that
the publishing-api handles all the updated_at, first_published_at, and
public_updated_at values that appear in the content store.  One side-effect
of this is that drafts of a manual have a null value for the
public_updated_at in the content store.  Note that we expect this for the
first draft of a new manual, but we're seeing it for other drafts too.
To avoid breaking manuals-frontend in this situation we add some guard
clauses to the presenter and helpers.
For https://trello.com/c/OC3RskhE/63-timestamps-on-manuals and in response to changes in https://github.com/alphagov/manuals-publisher/pull/780
> Handle a manual's public_updated_at being null

- app/assets/javascripts/collapsible.js
- app/assets/javascripts/collapsible_collection.js
- app/assets/stylesheets/application.scss
Quick fix, doesn't fix all accessibility concerns with these toggles; eg ARIA states, odd tabbing behaviour on visually hidden links (patched but not fixed), etc.
The current heading toggles can’t be opened with a keyboard. By dynamically adding links inside the headings we get all the correct tabindex and focus behaviour.
https://www.gov.uk/guidance/content-design/what-is-content-design
* Use the ID of the heading as the href target
* Another JS listener listens for clicks on links. This has been reduced in scope to body links (for expanding/closing footnotes).
* Show section when focussing on hidden links
Because content is visually hidden, the links within the content blocks can still be tabbed too. Rather than tabbing to something you can’t see, which feels broken, if the section …
> Give keyboard access to collapsible headings

- README.md
The specialist-publisher repo was renamed to manuals-publisher some time
ago.
Note that there is now a new specialist-publisher repo but it isn't
responsible for publishing the manuals rendered by this frontend app.
> Rename specialist to manuals in README

- app/assets/stylesheets/application.scss
- app/views/manuals/index.html.erb
- app/views/manuals/show.html.erb
- app/views/manuals/updates.html.erb
This application hides the border bottom of the beta label for design
purposes.  That's fine in the existing behaviour, but for the A/B test
the beta label has other elements underneath it (e.g. breadcrumbs). This
means we should show the border bottom in those cases.
Trello: https://trello.com/c/V6PSacVC/336-changes-to-education-related-content-pages-as-part-of-the-new-navigation-in-manuals-frontend
HMRC Manual stays the same:
But the new manual now has the expected border bottom:
> Introduce border-bottom in beta label for A/B test

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/views/manuals/index.html+new_navigation.erb
- app/views/manuals/show.html+new_navigation.erb
- app/views/manuals/updates.html+new_navigation.erb
This PR moves the manual pages into a `column-two-thirds` layout in order to make space for side navigation.
Trello: https://trello.com/c/V6PSacVC/336-changes-to-education-related-content-pages-as-part-of-the-new-navigation-in-manuals-frontend
The manual page:
The manual section page:
The manual updates' page:
> Column two thirds in manuals ab test

- Gemfile
- Gemfile.lock
- spec/features/ab_testing_manuals_spec.rb
This commit takes advantage of the new test helpers created in
govuk_ab_testing that support RSpec and Capybara.
More details in: https://github.com/alphagov/govuk_ab_testing/pull/17
Trelo: https://trello.com/c/V6PSacVC/336-changes-to-education-related-content-pages-as-part-of-the-new-navigation-in-manuals-frontend
> Use new `with_variant` from govuk_ab_testing gem

- app/controllers/application_controller.rb
- app/controllers/manuals_controller.rb
- app/views/layouts/application.html.erb
- app/views/manuals/index.html+new_navigation.erb
- app/views/manuals/show.html+new_navigation.erb
- app/views/manuals/updates.html+new_navigation.erb
- spec/features/ab_testing_manuals_spec.rb
Prior to this fix, the AB testing `meta` tag was only being applied to "B" variants of the rendered pages. This is incorrect, as it will fail to correctly track visits to "A" variants (and also manifests itself in not being able to switch A/B group in the Chrome plugin)
https://trello.com/c/djVxzKfU/442-investigate-weird-behaviour-where-the-a-b-test-option-doesn-t-always-show-from-the-chrome-extension
> Fix AB testing meta tags

- Gemfile
- Gemfile.lock
- app/models/education_navigation_ab_test_request.rb
- spec/features/ab_testing_manuals_spec.rb
- spec/rails_helper.rb
Main changes are:
- passing in the request headers to the variant checker;
- setting the acceptance testing framework in the configuration of the
gem.
Gem changes: https://github.com/alphagov/govuk_ab_testing/pull/20
Trello: https://trello.com/c/t4n8kPpx/434-make-sure-collections-can-be-toggled-with-the-a-b-test-and-react-to-it
> Upgrade govuk_ab_testing to 1.0.0

- app/assets/stylesheets/application.scss
This commit hides the "Give feedback" link from the manual's header,
because there will be a link to provide feedback always on that page at
the top.
Trello: https://trello.com/c/jHv8IAwx/470-remove-give-feedback-about-this-page-link-from-b-variant-of-manuals-frontend
> Hide "Give feedback" link on Education A/B test

- Gemfile
- Gemfile.lock
- app/presenters/manual_presenter.rb
- app/views/manuals/_taxonomy_sidebar.html.erb
- app/views/manuals/index.html+new_navigation.erb
- app/views/manuals/show.html+new_navigation.erb
- app/views/manuals/updates.html+new_navigation.erb
- spec/features/ab_testing_manuals_spec.rb
- spec/support/manual_helpers.rb
Add the taxonomy sidebar component from static and rework the tests to
assert for the presence of the sidebar where appropriate.
> Add taxonomy sidebar to new navigation pages

- Gemfile
- Gemfile.lock
- app/models/education_navigation_ab_test_request.rb
- spec/features/ab_testing_manuals_spec.rb
This means we can toggle the A/B variant in production via the chrome
extension. When we rollout the new navigation with a Fastly
configuration change, the % of users we select will start seeing these
new pages.
Trello: https://trello.com/c/940kowVa/484-remove-enable-new-navigation-check-from-repos-and-from-puppet
> Remove the New Navigation feature flag

- Gemfile
- Gemfile.lock
- app/controllers/manuals_controller.rb
- app/models/education_navigation_ab_test_request.rb
- app/views/layouts/application.html.erb
- app/views/manuals/_content_for_head_tag.html.erb
- app/views/manuals/index.html+new_navigation.erb
- app/views/manuals/index.html.erb
- app/views/manuals/show.html+new_navigation.erb
- app/views/manuals/show.html.erb
- app/views/manuals/updates.html+new_navigation.erb
- app/views/manuals/updates.html.erb
- spec/features/ab_testing_manuals_spec.rb
Ensure that only pages in the navigation A/B test (those which are tagged to taxons) are cached separately and tracked in the A/B test analytics.
https://trello.com/c/Xehe42eM/464-only-add-a-b-meta-tag-to-pages-in-the-navigation-a-b-test
> Only add A/B testing Vary header and meta tag to education pages

- Gemfile.lock
The list of document types which appear in the sidebar has changed. This gem upgrade picks up the latest version.
https://trello.com/c/RhEocgyj/42-remove-notices-from-guidance-list
> Update navigation helpers gem to pick up the latest taxonomy sidebar

- Gemfile.lock
- app/views/manuals/index.html+new_navigation.erb
- app/views/manuals/show.html+new_navigation.erb
- app/views/manuals/updates.html+new_navigation.erb
- spec/features/ab_testing_manuals_spec.rb
Upgrade the govuk_navigation_helpers gem to pick up the latest breadcrumb config. This adds the taxon back link on mobile.
https://trello.com/c/Y7OirowB/472-mobile-version-of-breadcrumbs-should-only-show-previous-link
> Convert taxon breadcrumbs to back link on mobile

- Gemfile
- Gemfile.lock
- app/assets/javascripts/mouseflow.js
- app/controllers/application_controller.rb
- app/models/benchmarking_ab_test_request.rb
- app/views/layouts/application.html.erb
- config/application.rb
- spec/features/ab_testing_manuals_spec.rb
- spec/features/benchmarking_spec.rb
We are going to conduct a 2nd round of Benchmarking in GOV.UK. The idea is that we will try it with the new Education Navigation enabled across GOV.UK and see how it performs against the current navigation patterns (mainstream browse pages, topics, etc).
Besides checking if people actually complete the tasks, we would also like to know more details about how they use the new navigation pages and also about the new orientation in content pages. In order to do that, we will track mouse movements and gather the results in a heatmap. We are using a software called mouseflow to do this.
The tracking code will only be present for the people doing the benchmarking test (around 60 people). It will be behind a new A/B test so the tracking doesn't run for other GOV.UK users. These 60 users will be …
> Mouse tracking

- config/environments/development.rb
This commit adds a development-specific configuration to ensure the frontend uses the assets subdomain for all assets rather than “www”.
Before:
After:
> Display assets correctly on development

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- spec/contracts/govuk_content_schemas_spec.rb
- spec/rails_helper.rb
- spec/support/app_helpers.rb
- spec/support/slimmer.rb
We're seeing high memory usage for manuals-frontend that corresponds with component memory leaks.
* Fix memory leak with components: https://github.com/alphagov/slimmer/pull/191
* Stub locale requests: https://github.com/alphagov/slimmer/pull/159
cc @h-lame @tijmenb @cbaines 
* Fix memory leak in components
* Bugfix for request URI's encoded as ASCII
* Bugfix for caching behaviour
* Use `Rails.cache` as the cache for templates, locales and components. You can
remove `config.slimmer.use_cache` for your application, as you can no longer
opt-out of caching.
* Add a `User-Agent` header to all outgoing API requests
* Removes the need_id meta tag, which is no longer used.
* Removes the functionality for breadcrumbs, related links and artefact-powered
metatags.
* Drop support for old Rails & …
> Bump slimmer from 9.0.1 to 10.1.3

- Gemfile
- Gemfile.lock
This fixes the issue with repeated related links across different
taxons.
Trello: https://trello.com/c/I4rs80n1/80-remove-duplicated-related-links-across-all-parent-taxons
> Upgrade to govuk_navigation_helpers 6.0.1

- Gemfile
- Gemfile.lock
[Trello](https://trello.com/c/J8ofEnrt/167-display-curated-related-links-in-the-sidebar)
To keep up to date with:
- govuk_navigation_helpers (https://github.com/alphagov/govuk_navigation_helpers/blob/master/CHANGELOG.md#630)
- gds_api_adapters (https://github.com/alphagov/gds-api-adapters/blob/master/CHANGELOG.md#4600)
> Bump gem versions

- app/assets/stylesheets/application.scss
* Adjusted position of magnifying glass icon on submit button for high density screens
* Fixed height of search box on mobile to match height of submit button
* Adjusted height of button to even number for general height matching
* Fixes #183
**Before, desktop**
**After, desktop**
**Before, mobile**
**After, mobile**
Internet Explorer 9...
Before
After:
The only difference I've made is that the input and the button are now both a little taller. It looks exactly the same in every newer version of IE as well.
I can fix this by explicitly setting a px height for the input (allowing for padding), but that feels wrong.
> Manual search box visual fixes

- app/assets/stylesheets/application.scss
- removing outer negative margin so box aligns with thin bar beneath header.
- https://trello.com/c/fOALAER3/5-global-header-bar-looks-odd-on-small-viewports-186
- fixes https://github.com/alphagov/manuals-frontend/issues/186
**Before**
**After**
> Fix inconsistent header appearance for manuals on mobile

- app/assets/stylesheets/application.scss
Adding padding to the top of `p` elements in collapsible subsections
adds extra padding to govspeak components like callouts, warnings, step
numbers, etc. which makes them render incorrectly.
This margin should not be required elsewhere, because govspeak `p`
elements have bottom margin. The margin at the top is covered by
the margin introduced by the body wrapper.
https://govuk.zendesk.com/agent/tickets/2260672
> Remove unneeded paragraph padding from collapsible sections

- app/helpers/application_helper.rb
- app/views/manuals/_taxonomy_beta_label.html.erb
- spec/unit/application_helper_spec.rb
For: https://trello.com/c/Bo5SQrIm/215-add-page-tracking-custom-dimension-into-education-beta-survey-banner
This lets the survey team know where each response has come from and
allows them to filter by section of the site.
> Add current_path to the survey link in the beta banner

- app/controllers/manuals_controller.rb
- spec/features/viewing_a_manual_spec.rb
We are now the canonical source of data on HMRC manuals, as such
we should index the data in external search engines.
https://trello.com/c/47KVsqpb/290-hmrc-manuals-in-external-search
> Allow HMRC manuals to be indexed

- Gemfile
- Gemfile.lock
- config/routes.rb
Slimmer is erroring under a certain set of inputs but catching the error – this leads to an invalid page being cached and served to users. By letting the error through we will serve a 500, the page will not be cached and users will see the correct content.
When a request is made for an unsupported format, eg text/javascript, the lack of a respond_to block meant we attempted to render it without a layout.
This led to a body being sent to slimmer without a #wrapper element,
causing the error:
`> undefined method 'to_html' for nil:NilClass`
in the BodyInserter processor
This matches: https://github.com/alphagov/finder-frontend/pull/271
> Fix caching problems and return 406 when necessary

- Gemfile
- Gemfile.lock
- lib/tasks/publishing_api.rake
It will soon be a requirement to send `update_type` with PUT content requests to the Publishing API, and sending `update_type` with Publish request is being deprecated.  In this PR we update PUT content and Publish requests in preparation for this change.  We also upgrade `gds-api-adapters` to bring this app up to date with the new expected behaviour.
[Trello](https://trello.com/c/LnJlkb9e/29-5-deprecate-the-usage-of-updatetype-in-publish-for-publishing-api-and-update-usage-across-govuk)
> Send update_type with put content

- config/application.rb
This commit changes `autoload_paths` to `eager_load_paths` when loading
`/lib` to ensure that this is loaded as it currently isn't being correctly loaded when run in `production` env.
> Load `/lib`

- Jenkinsfile
Hey :wave: !
This PR will enable a set of [end-to-end tests](https://github.com/alphagov/publishing-e2e-tests) to run every time a commit is made to this repo. :boom:
You can read through the scenarios at a [high level](https://docs.google.com/document/d/164Y8IEhPKawPo0VyTk5nmU_J6JFnRuA7iwOFgmu98ok/edit), and the capybara [here](https://github.com/alphagov/publishing-e2e-tests/tree/master/spec/manuals_publisher).
Look at the merge box below and you'll see a new check performed on this PR.
Enabling these tests will give increased confidence when making changes to this repo that the change doesn't break the publisher in an end-to-end environment.   The downside is that running these tests takes time, with build times between 6 - 11 minutes currently.
> Run manuals publisher end to end tests downstream job as part of CI

- Gemfile
- Gemfile.lock
Mainly for the new print styles for task lists.
Trello card: https://trello.com/c/9CD3dY7r/409-add-task-list-print-styles-to-apps
> Bump components gem to 3.2.0

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/initializers/logstasher.rb
We follow the guide in the changelog for govuk_app_config for going to
1.0.  We also remove the following stanza from config/production.rb:
$real_stdout = $stdout.clone
$stdout.reopen($stderr)
It's not mentioned in the govuk_app_config readme, but those lines are in
govuk_app_config now, so I suspect we don't need them in ours.
> Upgrade to govuk_app_config v 1.2.1

- app/controllers/application_controller.rb
- app/views/manuals/index.html.erb
- spec/features/viewing_a_manual_spec.rb
- spec/support/manual_helpers.rb
Step by step navigation content is now held in content items.  The helpers have
been updated appropriately, and are now held in govuk_publishing_components as
they are so tightly coupled to the components themselves.
https://trello.com/c/aHTclade/443-manuals-frontend-renders-step-by-step-navigation-from-content-item
> Render step nav content from content item

- app/views/layouts/application.html.erb
Manuals frontend doesn't set analytics tags. It probably should.
> Add analytics tags to manuals frontend

- app/models/manual.rb
- spec/unit/manual_spec.rb
https://sentry.io/govuk/app-manuals-frontend/
We've seen a [bunch of errors in Sentry](https://sentry.io/govuk/app-manuals-frontend/issues/529442718) where `content_store_manual` does not have a title.
The root cause is that content item doesn't have a title, this is possibly something wrong upstream with the data [hmrc-manuals-api](https://github.com/alphagov/hmrc-manuals-api) receives from HMRC.
```
irb(main):006:0> ContentItem.where(id: "/hmrc-internal-manuals/vat-civil-evasion-penalty").first
=> #<ContentItem _id: /hmrc-internal-manuals/vat-civil-evasion-penalty,  ... title: nil, description:
```
> Handle nil titles

- app/models/section.rb
- app/views/manuals/_manual.html.erb
- app/views/manuals/_manual_section.html.erb
- spec/features/viewing_a_manual_spec.rb
https://trello.com/c/ZMVwIyj5/28-move-the-govspeak-component-to-the-gem
> Use govspeak component from gem

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/views/manuals/_header.html.erb
- app/views/manuals/index.html.erb
- app/views/manuals/show.html.erb
- app/views/manuals/updates.html.erb
- spec/features/viewing_a_manual_spec.rb
- spec/support/app_helpers.rb
This makes the app use the phase banner from the gem (https://trello.com/c/qtXCDGQI). Since this is the last usage of Static components, we can clean up the code and test helpers.
https://trello.com/c/pU7YINt1
> Use phase banner from gem

- Gemfile
- Gemfile.lock
- app/views/manuals/_manual_section.html.erb
https://trello.com/c/BUij6N3Y/361-turn-on-bold-for-whitehall
Rich govpseak will be enabled by default.
Depends on: https://github.com/alphagov/govuk_publishing_components/pull/463
> Remove rich_govspeak option

- app/assets/stylesheets/_reset.scss
https://trello.com/c/BUij6N3Y/361-turn-on-bold-for-whitehall
Removes explicit reset of `<strong>` elements.
Related to https://github.com/alphagov/manuals-frontend/pull/436, the `.rich-govspeak` class would override this reset.
> Remove strong elements from reset to enable bold

- Gemfile
- Gemfile.lock
- spec/features/viewing_a_manual_spec.rb
- spec/support/capybara.rb
- spec/support/govuk_test.rb
https://trello.com/c/0QzuQFMb/415-epic-switch-app-test-suites-from-poltergeist-to-headless-chrome-using-govuktest
Poltergeist is no longer maintained so switch to Capybara::RackTest and where applicable Selenium chrome headless driver via alphagov/govuk_test.
> Replace poltergeist with govuk test

- app/assets/stylesheets/application.scss
- assumes a white background but the component is used on a blue background so links are invisible
- this is a short term fix while we get the component updated to have an option to allow for this scenario
Fixes this:
Example demo URL (fixed): https://govuk-manuals-frontend-pr-531.herokuapp.com/guidance/prevent-groundwater-pollution-from-underground-fuel-storage-tanks
Example live URL (broken): https://www.gov.uk/guidance/prevent-groundwater-pollution-from-underground-fuel-storage-tanks
> Override link colour in metadata component

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/presenters/manual_presenter.rb
Use the [inverse option](https://github.com/alphagov/govuk_publishing_components/pull/657) for the metadata component to provide a more robust solution to [this PR](https://github.com/alphagov/manuals-frontend/pull/531).
> Use inverse metadata option

- app/controllers/manuals_controller.rb
- app/views/manuals/index.html.erb
- spec/features/viewing_a_manual_spec.rb
- spec/support/app_helpers.rb
This adds the standard `Article` schema to the manual page (not sections
as yet).
We may look at adding the `HasPart` and `IsPartOf` schemas to manuals and
sections, but we'll plan this separately.
Adding a `SearchAction` to manuals pages is coming soon, and will happen
automatically when the publishing components gem is updated with the changes.
You can check that this works by looking at: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fgovuk-manuals-frontend-pr-649.herokuapp.com%2Fguidance%2Fthe-highway-code which analyses the review app's highway code manual page.
https://trello.com/c/4EAytHVV/747-plan-indexing-of-finder-pages
> Add machine readable metadata to manuals

- app/assets/javascripts/modules/collapsible.js
- app/assets/javascripts/modules/collapsible_collection.js
- app/assets/stylesheets/application.scss
- spec/javascripts/collapsible_collection_spec.js
- spec/javascripts/collapsible_spec.js
Some issues have been pointed out with the implementation of the accordion functionality on the following page template:
https://www.gov.uk/guidance/how-to-publish-on-gov-uk/accessible-pdfs
Current manuals accordion is an improvement on the previous implementation but not as accessible (to screen readers) as the implementation in the service manual e.g https://www.gov.uk/service-manual/design
Ideally we'd use the https://govuk-publishing-components.herokuapp.com/component-guide/accordion component but as this content is generated with govspeak, that isn't possible.
This PR adds fixes present in the above linked component
- Updates markup to use `button` instead of `a`
- Adds aria-expanded attribute to the button to announce state change to screenreaders
- Adds a handleClick function that …
> Accordion accessibility fixes

- Gemfile
- Gemfile.lock
- Updates govuk_publishing_components to 20.5.1
- Brings back govuk_frontend_toolkit direct dependency as it uses javascript from it
Supersedes #721
> Update app dependencies

- app/controllers/application_controller.rb
- spec/features/viewing_a_manual_spec.rb
Trello: https://trello.com/c/1cpCsNwa/174-unauthenticated-user-accessing-a-manuals-frontend-page-with-step-by-step-token-is-directed-to-sign-on
Follows on from: [RFC 113: Expanding draft access for unauthenticated users to allow multi-page fact checks](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-113-expanding-draft-access-for-unauthenticated-users.md)
At the moment manuals-frontend is throwing a 500 when it receives
an error code it doesn't recognise from content-store. That means
that users are shown a "Problem has occurred" page.
We need to handle this error properly so that in the case of a
403, the user will be properly routed to signon and asked to login
if there is any form of access limiting on the content item (e.g.
hosted on draft stack, access limited to organisation)
> Rescue 403 errors from content store

- app/assets/stylesheets/application.scss
- app/views/manuals/_manual_updates.html.erb
- spec/features/viewing_manual_updates_spec.rb
- spec/support/manual_helpers.rb
Change notes (or updates) are currently rendered all on one line, which can be hard to read.
This preserves line breaks in the change notes.
Before
After
[Trello](https://trello.com/c/rdNti5Hh/1670-5-investigate-allowing-line-breaks-in-change-notes)
> Allow new lines to show in change notes

- app/assets/stylesheets/_manuals-print.scss
Currently when users print a manual, H2s appear smaller than H3s.
This tweaks the button styles to appear larger.
[Live preview](https://manuals-fron-fix-print-m9kczh6.herokuapp.com/guidance/the-highway-code/rules-for-pedestrians-1-to-35)
**Before**
**After**
fixes #825
> Fix heading print style

- .rubocop.yml
- Gemfile
- Gemfile.lock
- lib/tasks/lint.rake
- lib/tasks/publishing_api.rake
- See commits for more details.
https://trello.com/c/pR7GEFfU/128-make-all-current-govuk-repos-use-rubocop-govuk-instead-of-govuk-lint
as part of the developer tooling group.
> Use `rubocop-govuk` instead of `govuk-lint`

- Rakefile
- script/cucumber
This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.
> Make entire repository pass Rubocop linting

- Rakefile
- lib/tasks/lint.rake
- spec/contracts/govuk_content_schemas_spec.rb
- spec/features/viewing_a_manual_spec.rb
- spec/support/manual_helpers.rb
- This is a prerequisite for being able to move more of our apps to
GitHub Actions. We want one single step bundle exec rake that runs
everything. This ensures parity between local dev and what CI runs
(something that we don't always have now).
https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
> Run RuboCop as part of `bundle exec rake` defaults

- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This allows asset host to be set by ASSET_HOST env var rather than
GOVUK_ASSET_HOST. This is in preparation for the assets of this app
changing hostname from assets.publishing.service.gov.uk to
www.gov.uk.
As part of this change the path to assets is changed to
/assets/manuals-frontend
The expectation is that this env var will only be set in dev
environments when proxying isn't set up for router.
> Switch asset host to www

- app/models/change_notes.rb
- spec/features/viewing_manual_updates_spec.rb
- spec/support/app_helpers.rb
- spec/support/manual_helpers.rb
- spec/unit/change_notes_spec.rb
This PR fixes date ordering on the manuals updates page. Previously, HMRC manuals displayed updates from earliest to most recent, whereas other manuals displayed updates from most recent to the earliest.
The reason for this is because the change notes for HMRC manuals, as recorded in the content item, ranged from most recent to earliest, whereas for other manuals was from earliest to most recent. A `reverse` operation was then applied to these change notes in the code, which meant that HMRC manuals were then displayed in the wrong order.
To resolve this, instead sort by date descending to ensure ordering is consistent for different manuals.
Raised from [this Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4181394).
> Fix date ordering on manuals updates page

- app/assets/stylesheets/application.scss
Replace the CSS for hiding accordion content with `display: none`
Currently, screen reader users and keyboard only users have to go through all the content of each accordion, meaning it's not possible to skim each accordion and only open the ones that the user actually wants to read. This fails WCAG SC 4.1.2 (buttons) and 3.2.1 or 1.3.2 (keyboard). This change ensures that content is hidden when collapsed and shown when not, which screen readers recognise when navigating the page.
**Card:** https://trello.com/c/R5qH7sOM/331-manuals-accordion-not-working-for-screen-reader-and-keyboard-only-users
> Replace accordion content hiding solution with display: none

- app/views/layouts/application.html.erb
- app/views/manuals/_header.html.erb
Moved phase banner and contextual breadcrumbs outside of main in manuals
frontend. 
`<main>` should only contain elements that are unique to the
document, which the breadcrumbs and phase banner are not.
This should not result in any visual changes
https://trello.com/c/UbK2Cher
> Move phase banner and contextual breadcrumbs

- app/views/manuals/_manual.html.erb
- app/views/manuals/_manual_section.html.erb
Updates the way the Govspeak component to not use the content parameter.
The Govspeak component should not be used with the content parameter as that will be deprecated; it should use a do block wrapped around sanitized markup instead.
See alphagov/govuk_publishing_components#1632 for more info.
None.
> Update govspeak component usage

- app/views/manuals/_manual.html.erb
- app/views/manuals/_manual_section.html.erb
This reverts https://github.com/alphagov/manuals-frontend/pull/995 as the added sanitize call is causing table markup to fail. Initially overlooked as checked pages didn't contain tables. Will look at safer implementation after reverting.
> Revert calls to govspeak component

- app/views/manuals/_manual.html.erb
- app/views/manuals/_manual_section.html.erb
This is a reimplementation of https://github.com/alphagov/manuals-frontend/pull/995
It updates the way that the govspeak component is called as the content parameter will be deprecated. It should use a do block ideally wrapped around sanitized markup. In the previous PR we sanitized the input but this failed embarrassingly in production and had to be reverted.
I investigated a more permissive sanitize attempt with exceptions, but while some pages, such as https://www.gov.uk/hmrc-internal-manuals/child-benefit-technical-manual/cbtm02120 would benefit from this approach if we allowed table syntax, other pages are more complex. To get https://www.gov.uk/guidance/mot-inspection-manual-for-private-passenger-and-light-commercial-vehicles/3-visibility to render properly I had to specify …
> Update govspeak component implementation

- app/views/manuals/_manual_section.html.erb
Removing a extra render of the body text in the manual section.
> Fix duplicated body text in manual section

- .github/pull_request_template.md
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
This is part of enabling automatic deployments for this app.
:warning: This application is Continuously Deployed: :warning:
- Merged changes are automatically deployed to staging and production.
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) **before** you merge.
- Check your branch is being deployed in the [Release app](https://release.publishing.service.gov.uk/applications/manuals-frontend), after merging.
> Add PR template before enabling automatic deploys

- app/views/manuals/_hmrc_callout.html.erb
- app/views/manuals/_manual.html.erb
- app/views/manuals/_manual_section.html.erb
- spec/features/viewing_a_manual_spec.rb
The markup for the callout was taken from the [component guide](https://components.publishing.service.gov.uk/component-guide/govspeak/warning_callout) example. The wording has been agreed with HMRC.
This callout will appear on HMRC content only.
- https://manuals-fron-warning-ca-fvwxpf.herokuapp.com/hmrc-internal-manuals/international-manual  
- https://manuals-fron-warning-ca-fvwxpf.herokuapp.com/hmrc-internal-manuals/international-manual/intm120000
- https://manuals-fron-warning-ca-fvwxpf.herokuapp.com/hmrc-internal-manuals/international-manual/intm120010
https://trello.com/c/yR4zJzdA/717-spike-hmrc-manuals-callout
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …
> HMRC manual warning callouts

- app/assets/stylesheets/_manuals-print.scss
- app/assets/stylesheets/application.scss
- app/views/manuals/_manual_updates.html.erb
This adds a `<br>` and uses `<p>` so the updates list is easier to read when printed as a PDF.
To review:
1. compare the following page on the live site with that on the review app:
- live: https://www.gov.uk/guidance/test-family-procedures-rules/updates
- review: https://manuals-fron-bilbof-imp-inj3ce.herokuapp.com/guidance/test-family-procedures-rules/updates
2. Click "Print this page" at the bottom to view the PDF
Ticket: https://govuk.zendesk.com/agent/tickets/4461812
> Improve print view of manual updates list

- app/views/manuals/_manual_updates.html.erb
Change notes (what we render on /guidance/`<manual>`/updates) can have newline characters. We were stripping them, which makes it hard to read (and worse when printing the page).
Using [simple_format](https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format) renders the newlines instead, making the page easier to read.
simple_format also sanitizes the change notes.
> Render newlines in manual update notes

- app/models/document.rb
- app/views/manuals/_manual_section.html.erb
Adds an id attribute to the `heading` object on accordion rendering, as well as the `anchor_navigation` feature flag to allow anchor navigation on manuals page accordions.
Part of a fix of the previous feature allowing manuals to link to individual accordion sections on other manuals.
requires [this PR on the components gem](https://github.com/alphagov/govuk_publishing_components/pull/1937) to be released before his can be merged and deployed.
No visual changes.
> Add anchor navigation feature flag to accordions

- app/controllers/application_controller.rb
- spec/rails_helper.rb
- spec/requests/request_spec.rb
We've had a number of Sentry issues to do with requesting JSON or
JS versions of Manuals Frontend pages:
- https://sentry.io/organizations/govuk/issues/2152998596/?project=202235&query=is%3Aunresolved
- https://sentry.io/organizations/govuk/issues/2161602206/?project=202235&query=is%3Aunresolved
The correct thing to do is to respond with a [406](https://httpstatuses.com/406),
and not to log inactionable Sentry issues.
I've taken inspiration from Content Publisher for the request
testing, and the underlying fix is the same approach as in
government-frontend:
https://github.com/alphagov/government-frontend/blob/ce26ae94d66d9ce92ac37028854211741ef44b8b/app/controllers/content_items_controller.rb#L6-L7
We will also need to do some work to ensure that 406 responses
are cached in Fastly. …
> Return 406 Not Acceptable when 'Accepts' header requests non-HTML

- app/assets/stylesheets/_manuals-print.scss
- app/assets/stylesheets/application.scss
- app/views/manuals/_header.html.erb
- app/views/manuals/_manual_breadcrumbs.html.erb
- app/views/manuals/_manual_section.html.erb
- app/views/manuals/_manual_updates.html.erb
- app/views/manuals/index.html.erb
- app/views/manuals/show.html.erb
- app/views/manuals/updates.html.erb
- spec/support/app_helpers.rb
The following items have been updated:
- H1 headings now use the heading component. The issue of having 2 H1s is recognised but not being tackled at this point.
- Search box now uses the search component
- Breadcrumbs now use breadcrumbs component: ~NOTE: **BLOCKED** AWAITING APPROVAL FROM HMRC - We may need to extend the component to accommodate the current page final crumb.~ Approval to move the final crumb to the start of the heading has been given.
- The feedback link has been removed as it duplicates functionality as the feedback component is at the bottom of the page.
Linked Trello: https://trello.com/c/1ooPxPEP/563-update-manuals-frontend-to-use-components
Sample pages:
* https://www.gov.uk/guidance/content-design - ([dev.gov.uk](http://manuals-frontend.dev.gov.uk/guidance/content-d …
> Replace bespoke code with components

- app/views/manuals/_manual_section.html.erb
A change to add the breadcrumb to the document heading for
manual_section view has caused the title to sometimes appear twice.
The document_heading is intended to present the `section_id - title`.
The intention is that the `breadcrumb` method should provide the `section_id` - however
if this is not present it nstead defaults to `title`.
https://github.com/alphagov/manuals-frontend/blob/63c17fff271e85fcf9f6196963e0d4135214c29f/app/models/document.rb#L26
This change prevents the title being added to the document_heading if it
is already present i.e: the `breadcrumb` method was unable to return a `section_id`.
> Prevent manual_section title from appearing twice

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/manuals/_manual_section.html.erb
- app/views/manuals/_manual_updates.html.erb
- app/views/manuals/show.html.erb
- app/views/manuals/updates.html.erb
Sets a two thirds limit on desktop for manual body content where accordions are rendered.
Additionally, this PR does some spring cleaning adjacent to this view:
- Adds a `govuk-width-container` class to the `id="wrapper"` content container div
- Replaces the lead paragraph on manuals with the [lead paragraph component](https://components.publishing.service.gov.uk/component-guide/lead_paragraph)
This is in response to feedback from department publishers that accordions are now very long which isn't a good experience for magnification users.
[Card](https://trello.com/c/wfX1mzXP/675-fix-accordion-column-text-width)
- https://www.gov.uk/guidance/how-to-publish-on-gov-uk/creating-and-updating-pages
- https://www.gov.uk/guidance/working-safely-during-coronavirus-covid-19/updates
- …
> Apply two thirds width to accordion sections in manuals and manual updates

- app/views/manuals/_manual.html.erb
Fixes a bug on manual contents pages ([Example](https://www.gov.uk/guidance/style-guide)) where the lead paragraph is too small by replacing it with the [lead paragraph component](https://components.publishing.service.gov.uk/component-guide/lead_paragraph).
This bug was introduced accidentally in https://github.com/alphagov/manuals-frontend/pull/1085 when the `summary` class was removed but this instance of it was missed.
> Add lead paragraph component to contents page view

- app/models/document.rb
- app/models/section.rb
- app/views/manuals/_manual_section.html.erb
- spec/features/viewing_a_manual_spec.rb
- spec/support/manual_helpers.rb
Manual sections that are published as `"visually_expanded": true`
will render as flat text  without the "accordion" govuk_publishing_component.
https://components.publishing.service.gov.uk/component-guide/accordion
The default publishing option is `"visually_expanded": false`. If the
`visually_expanded` attribute is not set the section will also continue
to display as an accordion.
Also removes an unused `collapsible?` method from the Section model.
------
[govuk-content-schemas](https://github.com/alphagov/govuk-content-schemas/pull/1051)
[trello](https://trello.com/c/wgEKW9Ze/2398-5-allow-manuals-publisher-to-set-accordions-to-open)
> ManualSections that are"visually_expanded" render without accordions

- app/controllers/application_controller.rb
- app/controllers/manuals_controller.rb
- app/repositories/document_repository.rb
- spec/features/viewing_a_manual_spec.rb
- spec/support/manual_helpers.rb
Sentry error: https://sentry.io/organizations/govuk/issues/1752513075/?environment=production&project=202235&query=is%3Aignored
Previously the code would raise an error if `document_from_repository`
returned a document that had a status of 'Gone'. This was raised as
[HTTPGone][1] from gds-api-adapters as a result of receiving a 410 from
content-store.
Now 'Gone' pages and their corresponding exception are rescued and
handled by returning a 410 status code which in turn renders a [generic
410 error page][2].
I've also refactored the error handling logic as part of this work
which:
* moves all this behaviour to the manuals controller
* follows the pattern in [government-frontend][3]
[1]: https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/exceptions.rb#L90-L91
[2]: …
> Handle gone status

- app/views/manuals/_hmrc_callout.html.erb
- app/views/manuals/_manual.html.erb
- app/views/manuals/_manual_section.html.erb
- spec/features/viewing_a_manual_spec.rb
Remove Brexit callout from HMRC manuals. This PR reverts https://github.com/alphagov/manuals-frontend/commit/3cd22d7dd65a787283bc766736a4d82839638183
<table>
<tr><td>Before (with callout) </td><td>After (without callout)</td></tr>
<tr>
<td> 
</td>
<td>
</td>
</tr> 
</table>
- https://manuals-fron-remove-hmr-mlvyla.herokuapp.com/hmrc-internal-manuals/international-manual
- https://manuals-fron-remove-hmr-mlvyla.herokuapp.com/hmrc-internal-manuals/international-manual/intm120000
- https://manuals-fron-remove-hmr-mlvyla.herokuapp.com/hmrc-internal-manuals/international-manual/intm120010
Trello: https://trello.com/c/G9onGAh5/1478-remove-hmrc-manuals-callout-banner
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/developmen …
> Remove brexit callout from HMRC manuals

- bin/rails
- bin/rake
- bin/setup
- bin/yarn
- config.ru
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/backtrace_silencers.rb
- config/initializers/filter_parameter_logging.rb
Use Rails 6.1 defaults and update config by running `app:update`.
---
Trello:
https://trello.com/c/nWRFaLO3/2562-manually-bump-apps-to-rails-61
> Update to Rails 6.1

- app/assets/stylesheets/application.scss
- app/views/manuals/_hmrc_sections.html.erb
- app/views/manuals/_manual.html.erb
Apply the new link styles, from the latest release of GOV.UK Frontend, to this app.
As part of this, this PR also replaces the section lists seen on manuals index pages ([example](https://www.gov.uk/guidance/academies-financial-handbook)) with the [document list component](https://components.publishing.service.gov.uk/component-guide/document_list).
Part of an ongoing effort by the GOV.UK Frontend community and GOV.UK Accessibility team to ensure that we are using the latest link styles across all our apps to ensure that users benefit from improved link visibility.
- https://www.gov.uk/guidance/academies-financial-handbook
- https://www.gov.uk/hmrc-internal-manuals/pensions-tax-manual
- https://www.gov.uk/hmrc-internal-manuals/trusts-settlements-and-estates-manual/tsem9900
- …
> Apply new link styles to manuals

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
Update `manuals-frontend` to use the Design System-based page layout
Major benefits include performance improvements, accessibility improvements, and consistency with other applications.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
> Swap to `gem_layout`

- app/assets/stylesheets/application.scss
The section-list elements were reliant on a CSS reset for zero padding. This reset CSS was dropped when swapping from `core_layout` to `gem_layout` in #1173 but this regression was missed while doing the manual review.
Note: This issue is not yet in production but can be seen in integration.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
> Remove padding on section-list

- app/assets/javascripts/application.js
- app/assets/stylesheets/_manuals-print.scss
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
Swap print link on page to use [Print Link component](https://components.publishing.service.gov.uk/component-guide/print_link) from gem
Closes #1172 
Before > After
> Update to Print Link

- .dockerignore
- .github/workflows/ci.yaml
- Dockerfile
- config/puma.rb
As part of the new GOV.UK EKS, the Dockerfile is improved to match
other new Dockerfiles, e.g. [frontend Dockerfile](https://github.com/alphagov/frontend/pull/3005)
In addition:
1. Puma is used instead of unicorm as web server
2. GitHub Actions workflow is added to push image to ECR on merge to main
Ref:
1. [trello card](https://trello.com/c/dP4vi19p/835-package-manuals-frontend-for-migration)
> Improve Docker image for GOV.UK EKS

- app/assets/javascripts/application.js
Remove jQuery from this application.
- only jQuery was this document.ready equivalent for primaryLinks
- replacing this is possible but slightly complicated by browser compatibility issues
- so maybe we could remove it entirely
- we've already removed document.ready successfully elsewhere on GOV.UK without a direct replacement, and testing this here it seems to work as well
- primaryLinks is still initialised and runs successfully
We're removing jQuery from GOV.UK.
None.
> Remove jQuery from manuals-frontend
